import assert from 'node:assert/strict';
import pg from 'pg';
import { runWorker } from '../src/worker.mjs';
const {Pool}=pg,base=process.env.API_BASE_URL||'http://127.0.0.1:8787',token=process.env.ADMIN_API_TOKEN||'phase2-test-token',pool=new Pool({connectionString:process.env.DATABASE_URL});
async function call(path,{method='GET',body,key}={}){const r=await fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,...(body?{'content-type':'application/json'}:{}),...(key?{'idempotency-key':key}:{})},body:body?JSON.stringify(body):undefined});const p=await r.json();assert.ok(r.ok,`${method} ${path}: ${r.status} ${JSON.stringify(p)}`);return p}
const project='project-sol';
let j=await call(`/admin/projects/${project}/jobs`,{method:'POST',key:'echo-one',body:{jobType:'test_echo',targetType:'garment',targetId:'shirt-white',input:{hello:'sol'}}});
const same=await call(`/admin/projects/${project}/jobs`,{method:'POST',key:'echo-one',body:{jobType:'test_echo',input:{different:true}}});assert.equal(same.id,j.id);
await runWorker({pool,workerId:'worker-smoke-a',once:true,leaseSeconds:5});j=await call(`/admin/projects/${project}/jobs/${j.id}`);assert.equal(j.status,'completed');assert.equal(j.progress,100);assert.equal(j.output.echo.hello,'sol');assert.equal(j.events.some(e=>e.event_type==='claimed'),true);
let retry=await call(`/admin/projects/${project}/jobs`,{method:'POST',key:'fail-once',body:{jobType:'test_fail_once',maxAttempts:3}});await runWorker({pool,workerId:'worker-smoke-b',once:true,leaseSeconds:5});retry=await call(`/admin/projects/${project}/jobs/${retry.id}`);assert.equal(retry.status,'retrying');await pool.query('UPDATE generation_jobs SET available_at=now() WHERE id=$1',[retry.id]);await runWorker({pool,workerId:'worker-smoke-b',once:true,leaseSeconds:5});retry=await call(`/admin/projects/${project}/jobs/${retry.id}`);assert.equal(retry.status,'completed');assert.equal(retry.attempt_count,2);
let cancelled=await call(`/admin/projects/${project}/jobs`,{method:'POST',key:'cancel-one',body:{jobType:'test_echo'}});cancelled=await call(`/admin/projects/${project}/jobs/${cancelled.id}/cancel`,{method:'POST'});assert.equal(cancelled.status,'cancelled');
let stale=await call(`/admin/projects/${project}/jobs`,{method:'POST',key:'stale-one',body:{jobType:'test_echo',input:{stale:true}}});await pool.query(`UPDATE generation_jobs SET status='processing',locked_by='dead-worker',lease_expires_at=now()-interval '1 second' WHERE id=$1`,[stale.id]);await runWorker({pool,workerId:'worker-recovery',once:true,leaseSeconds:5});stale=await call(`/admin/projects/${project}/jobs/${stale.id}`);assert.equal(stale.status,'completed');assert.equal(stale.attempt_count,1);
const ops=await call(`/admin/projects/${project}/ops/summary`);assert.ok(ops.counts.completed>=3);assert.ok(ops.workers.some(w=>w.worker_id==='worker-recovery'));const panel=await fetch(base+'/ops');assert.equal(panel.status,200);assert.match(await panel.text(),/Consola operativa/);
await pool.end();console.log('Phase 2D jobs and ops smoke: PASS');
