import { ApiError } from './errors.mjs';
import { withTransaction } from './db.mjs';
const J=JSON.stringify;
const row=r=>({...r,input:r.input||{},output:r.output||{},result_summary:r.result_summary||{}});
export async function createJob(pool,projectId,input,key){
 if(!key) throw new ApiError(400,'IDEMPOTENCY_REQUIRED','Idempotency-Key is required');
 if(!input?.jobType) throw new ApiError(422,'JOB_INVALID','jobType is required');
 const q=`INSERT INTO generation_jobs(project_id,job_type,target_type,target_id,idempotency_key,input,priority,max_attempts)
 VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8) ON CONFLICT(project_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING *`;
 return row((await pool.query(q,[projectId,input.jobType,input.targetType||null,input.targetId||null,key,J(input.input||{}),input.priority??100,input.maxAttempts??3])).rows[0]);
}
export async function listJobs(pool,projectId,{status,limit=50}={}){const values=[projectId];let where='project_id=$1';if(status){values.push(status);where+=` AND status=$${values.length}::job_status`}values.push(Math.min(Number(limit)||50,100));return(await pool.query(`SELECT * FROM generation_jobs WHERE ${where} ORDER BY created_at DESC LIMIT $${values.length}`,values)).rows.map(row)}
export async function getJob(pool,projectId,id){const r=await pool.query('SELECT * FROM generation_jobs WHERE project_id=$1 AND id=$2',[projectId,id]);if(!r.rowCount)throw new ApiError(404,'JOB_NOT_FOUND','Job not found');const events=await pool.query('SELECT event_type,from_status,to_status,actor,details,created_at FROM job_events WHERE job_id=$1 ORDER BY created_at',[id]);return{...row(r.rows[0]),events:events.rows}}
export async function requestCancel(pool,projectId,id){const r=await pool.query(`UPDATE generation_jobs SET cancel_requested_at=now(),status=CASE WHEN status IN('queued','retrying') THEN 'cancelled'::job_status ELSE status END,finished_at=CASE WHEN status IN('queued','retrying') THEN now() ELSE finished_at END,updated_at=now() WHERE project_id=$1 AND id=$2 AND status NOT IN('completed','failed','cancelled') RETURNING *`,[projectId,id]);if(!r.rowCount)throw new ApiError(409,'JOB_NOT_CANCELLABLE','Job cannot be cancelled');await pool.query(`INSERT INTO job_events(job_id,event_type,actor,details) VALUES($1,'cancel_requested','admin','{}')`,[id]);return row(r.rows[0])}
export async function retryJob(pool,projectId,id,key){if(!key)throw new ApiError(400,'IDEMPOTENCY_REQUIRED','Idempotency-Key is required');return withTransaction(pool,async c=>{const old=await c.query(`SELECT * FROM generation_jobs WHERE project_id=$1 AND id=$2 FOR UPDATE`,[projectId,id]);if(!old.rowCount)throw new ApiError(404,'JOB_NOT_FOUND','Job not found');const j=old.rows[0];if(!['failed','cancelled'].includes(j.status))throw new ApiError(409,'JOB_NOT_RETRYABLE','Job is not retryable');return createJob(c,projectId,{jobType:j.job_type,targetType:j.target_type,targetId:j.target_id,input:j.input,priority:j.priority,maxAttempts:j.max_attempts},key)})}
export async function claimJob(pool,workerId,leaseSeconds=30){return withTransaction(pool,async c=>{await c.query(`UPDATE generation_jobs SET status='retrying',locked_by=NULL,locked_at=NULL,lease_expires_at=NULL,available_at=now(),updated_at=now() WHERE status='processing' AND lease_expires_at<now() AND cancel_requested_at IS NULL`);const r=await c.query(`SELECT * FROM generation_jobs WHERE status IN('queued','retrying') AND available_at<=now() AND cancel_requested_at IS NULL ORDER BY priority,available_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1`);await c.query(`INSERT INTO worker_heartbeats(worker_id,last_seen_at,metadata) VALUES($1,now(),'{}') ON CONFLICT(worker_id) DO UPDATE SET last_seen_at=now()`,[workerId]);if(!r.rowCount)return null;const j=r.rows[0],attempt=j.attempt_count+1;const u=(await c.query(`UPDATE generation_jobs SET status='processing',attempt_count=$3,locked_by=$2,locked_at=now(),lease_expires_at=now()+($4||' seconds')::interval,last_heartbeat_at=now(),started_at=COALESCE(started_at,now()),updated_at=now() WHERE id=$1 RETURNING *`,[j.id,workerId,attempt,String(leaseSeconds)])).rows[0];await c.query(`INSERT INTO job_attempts(job_id,attempt_number,status,worker_id) VALUES($1,$2,'processing',$3)`,[j.id,attempt,workerId]);await c.query(`INSERT INTO job_events(job_id,event_type,from_status,to_status,actor) VALUES($1,'claimed',$2::job_status,'processing',$3)`,[j.id,j.status,workerId]);await c.query(`UPDATE worker_heartbeats SET current_job_id=$2,last_seen_at=now() WHERE worker_id=$1`,[workerId,j.id]);return row(u)})}
export async function heartbeat(pool,jobId,workerId,progress,leaseSeconds=30){const r=await pool.query(`UPDATE generation_jobs SET progress=$3,last_heartbeat_at=now(),lease_expires_at=now()+($4||' seconds')::interval,updated_at=now() WHERE id=$1 AND locked_by=$2 AND status='processing' RETURNING cancel_requested_at`,[jobId,workerId,progress,String(leaseSeconds)]);if(!r.rowCount)throw new ApiError(409,'LEASE_LOST','Worker lease lost');await pool.query(`UPDATE worker_heartbeats SET last_seen_at=now(),current_job_id=$2 WHERE worker_id=$1`,[workerId,jobId]);return{cancelRequested:Boolean(r.rows[0].cancel_requested_at)}}
export async function finishJob(pool,jobId,workerId,{output={},summary={}}={}){return settle(pool,jobId,workerId,'completed',output,summary)}
export async function failJob(pool,jobId,workerId,error){return withTransaction(pool,async c=>{const r=await c.query(`SELECT * FROM generation_jobs WHERE id=$1 AND locked_by=$2 AND status='processing' FOR UPDATE`,[jobId,workerId]);if(!r.rowCount)throw new ApiError(409,'LEASE_LOST','Worker lease lost');const j=r.rows[0],retry=j.attempt_count<j.max_attempts&&!j.cancel_requested_at,status=j.cancel_requested_at?'cancelled':retry?'retrying':'failed',code=error?.code||'JOB_FAILED',message=String(error?.message||'Job failed').slice(0,500);await c.query(`UPDATE generation_jobs SET status=$3::job_status,error_code=$4,error_message=$5,available_at=CASE WHEN $3::text='retrying' THEN now()+make_interval(secs=>LEAST(60,power(2,attempt_count)::int)) ELSE available_at END,finished_at=CASE WHEN $3::text IN('failed','cancelled') THEN now() ELSE NULL END,locked_by=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND locked_by=$2`,[jobId,workerId,status,code,message]);await c.query(`UPDATE job_attempts SET status=$3::job_status,finished_at=now(),error_code=$4,error_message=$5 WHERE job_id=$1 AND attempt_number=$2`,[jobId,j.attempt_count,status,code,message]);await c.query(`INSERT INTO job_events(job_id,event_type,from_status,to_status,actor,details) VALUES($1,'failed','processing',$2::job_status,$3,$4::jsonb)`,[jobId,status,workerId,J({code,message})]);await c.query(`UPDATE worker_heartbeats SET current_job_id=NULL,last_seen_at=now() WHERE worker_id=$1`,[workerId]);return{status}})}
async function settle(pool,jobId,workerId,status,output,summary){return withTransaction(pool,async c=>{const r=await c.query(`UPDATE generation_jobs SET status=$3::job_status,progress=100,output=$4::jsonb,result_summary=$5::jsonb,finished_at=now(),locked_by=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND locked_by=$2 AND status='processing' RETURNING *`,[jobId,workerId,status,J(output),J(summary)]);if(!r.rowCount)throw new ApiError(409,'LEASE_LOST','Worker lease lost');const j=r.rows[0];await c.query(`UPDATE job_attempts SET status=$3::job_status,finished_at=now() WHERE job_id=$1 AND attempt_number=$2`,[jobId,j.attempt_count,status]);await c.query(`INSERT INTO job_events(job_id,event_type,from_status,to_status,actor) VALUES($1,'completed','processing',$2::job_status,$3)`,[jobId,status,workerId]);await c.query(`UPDATE worker_heartbeats SET current_job_id=NULL,last_seen_at=now() WHERE worker_id=$1`,[workerId]);return row(j)})}
export async function opsSummary(pool,projectId){const counts=await pool.query(`SELECT status,count(*)::int count FROM generation_jobs WHERE project_id=$1 GROUP BY status`,[projectId]);const workers=await pool.query(`SELECT worker_id,last_seen_at,current_job_id,(last_seen_at>now()-interval '90 seconds') online FROM worker_heartbeats ORDER BY last_seen_at DESC`);return{counts:Object.fromEntries(counts.rows.map(r=>[r.status,r.count])),workers:workers.rows,recent:await listJobs(pool,projectId,{limit:25})}}
