import { createHash } from 'node:crypto';
import { mkdir,readFile,rename,rm,stat,writeFile } from 'node:fs/promises';
import path from 'node:path';
import { validateGarment,validateOutfit,ONTOLOGY } from '../../packages/fashion-schema/validate.mjs';
const J=JSON.stringify, sha=v=>createHash('sha256').update(v).digest('hex');
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const jsonHash=v=>sha(J(canonical(v)));
const asJson=v=>J(v??(Array.isArray(v)?[]:{}));
function uuid(seed){const h=sha(seed).slice(0,32).split('');h[12]='5';h[16]=((parseInt(h[16],16)&3)|8).toString(16);return `${h.slice(0,8).join('')}-${h.slice(8,12).join('')}-${h.slice(12,16).join('')}-${h.slice(16,20).join('')}-${h.slice(20).join('')}`}
function safeInside(root,file){const r=path.resolve(root),f=path.resolve(file);if(f!==r&&!f.startsWith(r+path.sep))throw new Error(`Unsafe asset path: ${file}`);return f}
function resolveRef(dataDir,ref){if(!ref||typeof ref!=='string')return null;let rel=ref.replace(/^https?:\/\/[^/]+/,'');if(rel.startsWith('/api/import/library/'))rel=`imported/${path.basename(rel)}`;else if(rel.startsWith('/api/import/assets/'))rel=`jobs/${rel.slice('/api/import/assets/'.length)}`;else if(rel.startsWith('/api/import/outfits/'))rel=`outfit-images/${path.basename(rel)}`;else rel=rel.replace(/^\/+/, '');return safeInside(dataDir,path.join(dataDir,rel))}
function mime(bytes){if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return'image/jpeg';if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')return'image/webp';throw new Error('Unsupported or spoofed asset format')}
const garmentFields=g=>({id:g.id,name:g.name,description:g.description||'',part:g.part||g.bodyArea,bodyArea:g.bodyArea||g.part,category:g.category??null,subcategory:g.subcategory??null,garmentType:g.garmentType??null,material:g.material??null,pattern:g.pattern??null,silhouette:g.silhouette??null,fit:g.fit??null,style:g.style??null,season:g.season||[],occasion:g.occasion||[],thermalWeight:g.thermalWeight??null,color:g.color??null,secondaryColor:g.secondaryColor??null,tags:g.tags||[],fieldProvenance:g.fieldProvenance||{},source:{...(g.source||{}),migration:'wardrobe-local'},review:g.review||{}});
const outfitFields=o=>({id:o.id,name:o.name,description:o.description||o.reason||'',style:o.style??null,occasion:o.occasion||[],season:o.season||[],tags:o.tags||[],status:ONTOLOGY.outfitStatus.values.includes(o.status)?o.status:'draft',source:o.source||'wardrobe-migration',garmentIds:o.garmentIds||[]});
export async function inventoryWardrobe({dataDir}){
 const library=JSON.parse(await readFile(path.join(dataDir,'library.json'),'utf8'));const raw=JSON.parse(await readFile(path.join(dataDir,'outfits.json'),'utf8').catch(e=>e.code==='ENOENT'?'{"outfits":[]}':Promise.reject(e)));const outfits=Array.isArray(raw)?raw:(raw.outfits||[]);if(!Array.isArray(library))throw new Error('library.json must be an array');
 const garments=library.map(garmentFields),byId=Object.fromEntries(garments.map(g=>[g.id,g]));for(const g of garments){const v=validateGarment(g);if(!v.ok)throw new Error(v.errors.join('; '))}for(const o0 of outfits){const o=outfitFields(o0),v=validateOutfit(o,byId);if(!v.ok)throw new Error(v.errors.join('; '))}
 const assets=[];const add=async(ownerType,ownerId,kind,ref)=>{const file=resolveRef(dataDir,ref);if(!file)return;const bytes=await readFile(file),s=await stat(file);assets.push({id:uuid(`${ownerType}|${ownerId}|${kind}|${ref}`),ownerType,ownerId,kind,ref,file,filename:path.basename(file),mimeType:mime(bytes),byteSize:s.size,checksum:sha(bytes)})};
 for(const g of library){await add('garment',g.id,'garment',g.image);if(g.modeledImage)await add('garment',g.id,'modeled',g.modeledImage);if(g.thumbnail&&g.thumbnail!==g.image)await add('garment',g.id,'thumbnail',g.thumbnail)}for(const o of outfits){await add('outfit',o.id,'editorial',o.image);await add('outfit',o.id,'flatlay',o.flatLayImage)}
 const normalizedOutfits=outfits.map(outfitFields);const fingerprint=jsonHash({garments,outfits:normalizedOutfits,assets:assets.map(({file,...a})=>a)});return{dataDir:path.resolve(dataDir),garments,outfits:normalizedOutfits,assets,fingerprint,counts:{garments:garments.length,outfits:normalizedOutfits.length,assets:assets.length},checksums:{library:jsonHash(garments),outfits:jsonHash(normalizedOutfits),assets:jsonHash(assets.map(a=>[a.id,a.checksum]))}}}
async function counts(c,p){const q=async t=>Number((await c.query(`SELECT count(*) n FROM ${t} WHERE project_id=$1`,[p])).rows[0].n);return{garments:await q('garments'),outfits:await q('outfits'),assets:await q('assets')}}
const same=(a,b)=>jsonHash(a)===jsonHash(b);
export async function migrateWardrobe({pool,storageRoot,projectId,inventory,dryRun=false}){
 const existing=await pool.query('SELECT * FROM migration_runs WHERE project_id=$1 AND source_fingerprint=$2 AND dry_run=$3',[projectId,inventory.fingerprint,dryRun]);if(existing.rowCount)return{run:existing.rows[0],idempotent:true};const client=await pool.connect();let runId,createdFiles=[];try{await client.query('BEGIN');const before=await counts(client,projectId);runId=(await client.query(`INSERT INTO migration_runs(project_id,source_fingerprint,status,dry_run,inventory,before_counts) VALUES($1,$2,'running',$3,$4::jsonb,$5::jsonb) RETURNING id`,[projectId,inventory.fingerprint,dryRun,J({counts:inventory.counts,checksums:inventory.checksums}),J(before)])).rows[0].id;
  const record=async(type,id,action,src=null,tgt=null,details={})=>client.query(`INSERT INTO migration_entities(run_id,entity_type,entity_id,action,source_checksum,target_checksum,details) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[runId,type,id,action,src,tgt,J(details)]);
  for(const g of inventory.garments){const r=await client.query('SELECT * FROM garments WHERE project_id=$1 AND id=$2',[projectId,g.id]);if(r.rowCount){const x=r.rows[0],current=garmentFields({id:x.id,name:x.name,description:x.description,part:x.part,bodyArea:x.body_area,category:x.category,subcategory:x.subcategory,garmentType:x.garment_type,material:x.material,pattern:x.pattern,silhouette:x.silhouette,fit:x.fit,style:x.style,season:x.season,occasion:x.occasion,thermalWeight:x.thermal_weight,color:x.color,secondaryColor:x.secondary_color,tags:x.tags,fieldProvenance:x.field_provenance,source:x.source,review:x.review});if(!same({...g,source:undefined},{...current,source:undefined}))throw new Error(`Garment conflict: ${g.id}`);await record('garment',g.id,'verified',jsonHash(g),jsonHash(current));continue}if(!dryRun)await client.query(`INSERT INTO garments(id,project_id,name,description,part,body_area,category,subcategory,garment_type,material,pattern,silhouette,fit,style,season,occasion,thermal_weight,color,secondary_color,tags,field_provenance,source,review) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16::jsonb,$17,$18,$19,$20::jsonb,$21::jsonb,$22::jsonb,$23::jsonb)`,[g.id,projectId,g.name,g.description,g.part,g.bodyArea,g.category,g.subcategory,g.garmentType,g.material,g.pattern,g.silhouette,g.fit,g.style,J(g.season),J(g.occasion),g.thermalWeight,g.color,g.secondaryColor,J(g.tags),J(g.fieldProvenance),J(g.source),J(g.review)]);await record('garment',g.id,dryRun?'skipped':'created',jsonHash(g),jsonHash(g));}
  for(const o of inventory.outfits){const r=await client.query('SELECT * FROM outfits WHERE project_id=$1 AND id=$2',[projectId,o.id]);if(r.rowCount){const ids=(await client.query('SELECT garment_id FROM outfit_items WHERE project_id=$1 AND outfit_id=$2 ORDER BY position',[projectId,o.id])).rows.map(x=>x.garment_id);const x=r.rows[0],current=outfitFields({...x,garmentIds:ids});if(!same(o,current))throw new Error(`Outfit conflict: ${o.id}`);await record('outfit',o.id,'verified',jsonHash(o),jsonHash(current));continue}if(!dryRun){await client.query(`INSERT INTO outfits(id,project_id,name,description,style,occasion,season,tags,status,source) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9,$10)`,[o.id,projectId,o.name,o.description,o.style,J(o.occasion),J(o.season),J(o.tags),o.status,o.source]);for(const[i,gid]of o.garmentIds.entries())await client.query('INSERT INTO outfit_items(project_id,outfit_id,garment_id,position) VALUES($1,$2,$3,$4)',[projectId,o.id,gid,i])}await record('outfit',o.id,dryRun?'skipped':'created',jsonHash(o),jsonHash(o));}
  for(const a of inventory.assets){const r=await client.query('SELECT * FROM assets WHERE id=$1',[a.id]);if(r.rowCount){if(r.rows[0].checksum_sha256!==a.checksum)throw new Error(`Asset conflict: ${a.id}`);await record('asset',a.id,'verified',a.checksum,a.checksum);continue}if(!dryRun){const ext=path.extname(a.filename).toLowerCase(),key=`projects/${projectId}/internal/${a.id}${ext}`,target=safeInside(storageRoot,path.join(storageRoot,key));await mkdir(path.dirname(target),{recursive:true});const tmp=`${target}.migration-${runId}`;await writeFile(tmp,await readFile(a.file),{mode:0o600});await rename(tmp,target);createdFiles.push(target);await client.query(`INSERT INTO assets(id,project_id,garment_id,outfit_id,kind,visibility,status,storage_key,mime_type,byte_size,checksum_sha256,original_filename,completed_at,metadata) VALUES($1,$2,$3,$4,$5,'internal','ready',$6,$7,$8,$9,$10,now(),$11::jsonb)`,[a.id,projectId,a.ownerType==='garment'?a.ownerId:null,a.ownerType==='outfit'?a.ownerId:null,a.kind,key,a.mimeType,a.byteSize,a.checksum,a.filename,J({sourceRef:a.ref,migrationRunId:runId})])}await record('asset',a.id,dryRun?'skipped':'created',a.checksum,a.checksum,{kind:a.kind,ownerType:a.ownerType,ownerId:a.ownerId});}
  const after=dryRun?before:await counts(client,projectId),comparison={expected:inventory.counts,delta:{garments:after.garments-before.garments,outfits:after.outfits-before.outfits,assets:after.assets-before.assets},matches:dryRun||['garments','outfits','assets'].every(k=>after[k]-before[k]===inventory.counts[k])};if(!comparison.matches)throw new Error('Post-migration count comparison failed');await client.query(`UPDATE migration_runs SET status='completed',after_counts=$2::jsonb,comparison=$3::jsonb,completed_at=now() WHERE id=$1`,[runId,J(after),J(comparison)]);await client.query('COMMIT');return{runId,before,after,comparison,idempotent:false,dryRun};
 }catch(e){await client.query('ROLLBACK').catch(()=>{});await Promise.all(createdFiles.map(f=>rm(f,{force:true})));throw e}finally{client.release()}}
export async function rollbackMigration({pool,storageRoot,runId}){const c=await pool.connect();const files=[];try{await c.query('BEGIN');const run=(await c.query(`SELECT * FROM migration_runs WHERE id=$1 FOR UPDATE`,[runId])).rows[0];if(!run||run.status!=='completed'||run.dry_run)throw new Error('Migration run is not rollbackable');const entities=(await c.query(`SELECT * FROM migration_entities WHERE run_id=$1 AND action='created' ORDER BY CASE entity_type WHEN 'asset' THEN 1 WHEN 'outfit' THEN 2 ELSE 3 END`,[runId])).rows;for(const e of entities){if(e.entity_type==='asset'){const r=await c.query('DELETE FROM assets WHERE id=$1 RETURNING storage_key',[e.entity_id]);if(r.rowCount)files.push(safeInside(storageRoot,path.join(storageRoot,r.rows[0].storage_key)))}else if(e.entity_type==='outfit')await c.query('DELETE FROM outfits WHERE id=$1 AND project_id=$2',[e.entity_id,run.project_id]);else await c.query('DELETE FROM garments WHERE id=$1 AND project_id=$2',[e.entity_id,run.project_id])}await c.query(`UPDATE migration_runs SET status='rolled_back',rolled_back_at=now() WHERE id=$1`,[runId]);await c.query('COMMIT');await Promise.all(files.map(f=>rm(f,{force:true})));return{runId,removed:entities.length}}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release()}}
